# SPDX-License-Identifier: MIT OR Apache-2.0
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: nuget
    directory: "/apps/desktop-relay"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
