# SPDX-License-Identifier: MIT OR Apache-2.0
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from conceptflow.mpl.v1 import perception_pb2 as conceptflow_dot_mpl_dot_v1_dot_perception__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in conceptflow/mpl/v1/perception_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PerceptionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Negotiate = channel.unary_unary(
                '/conceptflow.mpl.v1.PerceptionService/Negotiate',
                request_serializer=conceptflow_dot_mpl_dot_v1_dot_perception__pb2.NegotiateRequest.SerializeToString,
                response_deserializer=conceptflow_dot_mpl_dot_v1_dot_perception__pb2.NegotiateResponse.FromString,
                _registered_method=True)
        self.ProcessFrame = channel.unary_unary(
                '/conceptflow.mpl.v1.PerceptionService/ProcessFrame',
                request_serializer=conceptflow_dot_mpl_dot_v1_dot_perception__pb2.FramePayload.SerializeToString,
                response_deserializer=conceptflow_dot_mpl_dot_v1_dot_perception__pb2.PerceptionResult.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/conceptflow.mpl.v1.PerceptionService/Health',
                request_serializer=conceptflow_dot_mpl_dot_v1_dot_perception__pb2.HealthRequest.SerializeToString,
                response_deserializer=conceptflow_dot_mpl_dot_v1_dot_perception__pb2.HealthResponse.FromString,
                _registered_method=True)


class PerceptionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Negotiate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PerceptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Negotiate': grpc.unary_unary_rpc_method_handler(
                    servicer.Negotiate,
                    request_deserializer=conceptflow_dot_mpl_dot_v1_dot_perception__pb2.NegotiateRequest.FromString,
                    response_serializer=conceptflow_dot_mpl_dot_v1_dot_perception__pb2.NegotiateResponse.SerializeToString,
            ),
            'ProcessFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFrame,
                    request_deserializer=conceptflow_dot_mpl_dot_v1_dot_perception__pb2.FramePayload.FromString,
                    response_serializer=conceptflow_dot_mpl_dot_v1_dot_perception__pb2.PerceptionResult.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=conceptflow_dot_mpl_dot_v1_dot_perception__pb2.HealthRequest.FromString,
                    response_serializer=conceptflow_dot_mpl_dot_v1_dot_perception__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conceptflow.mpl.v1.PerceptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('conceptflow.mpl.v1.PerceptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PerceptionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Negotiate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conceptflow.mpl.v1.PerceptionService/Negotiate',
            conceptflow_dot_mpl_dot_v1_dot_perception__pb2.NegotiateRequest.SerializeToString,
            conceptflow_dot_mpl_dot_v1_dot_perception__pb2.NegotiateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conceptflow.mpl.v1.PerceptionService/ProcessFrame',
            conceptflow_dot_mpl_dot_v1_dot_perception__pb2.FramePayload.SerializeToString,
            conceptflow_dot_mpl_dot_v1_dot_perception__pb2.PerceptionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conceptflow.mpl.v1.PerceptionService/Health',
            conceptflow_dot_mpl_dot_v1_dot_perception__pb2.HealthRequest.SerializeToString,
            conceptflow_dot_mpl_dot_v1_dot_perception__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
