# SPDX-License-Identifier: MIT OR Apache-2.0
"""Headless Map. Morph. Move. perception primitives."""

from .audio import (
    AudioDispatch,
    AudioOutputTopology,
    FmodCommandAdapter,
    InspectableAudioFallback,
    SpatializerProfile,
    SpatialVoiceCommand,
)
from .body import BUBBLE_RADIUS_METERS, BodyClearance, BodyProfile, BodyProxy, BodyRegion
from .frames import FrameGraph
from .geometry import DepthSource, GeometryMapper, MetricGeometryObservation, StableManifold, SurfaceContact
from .model import CoordinateFrame, Quaternion, StaleTransformError, TimedTransform, Vec3, clamp01
from .morph import (
    EnvelopmentField,
    GeometryCue,
    GeometryMorpher,
    HapticCue,
    HapticPattern,
    IntrusionAnchor,
    SpeakerArrayConfig,
    SpeakerBank,
    VirtualEmitter,
    VirtualSpeakerArray,
    WeightedEmitter,
)
from .move import MotionGate, MotionGateConfig, MotionSample
from .providers import (
    DEPTH_ANYTHING_V2_METRIC_MODELS,
    DepthAnythingExternalConfig,
    DepthEnvironment,
    DepthProvider,
    MetricGeometryProvider,
    ObjectTracker,
    OpenVocabularySegmenter,
    PoseProvider,
    SceneDescriber,
    SemanticSegmenter,
)
from .pipeline import GeometryOutput, PerceptionEngine, PipelineCounters, SemanticOutput, SpatialMap
from .scheduler import PerceptualPriorityScheduler, PriorityLane, ScheduledCue, SchedulerCounters
from .semantic import (
    AuditoryIconCue,
    AuditoryIconDefinition,
    AuditoryIconRegistry,
    MaskDepthPoint,
    SceneDescriptionRequest,
    SceneSimilarityGate,
    SegmentedObservation,
    SemanticDepthFuser,
    SemanticGateConfig,
    SemanticSimilarityGate,
    SemanticTrack,
)

__all__ = [
    "BUBBLE_RADIUS_METERS",
    "BodyClearance",
    "BodyProfile",
    "BodyProxy",
    "BodyRegion",
    "CoordinateFrame",
    "DepthSource",
    "DepthAnythingExternalConfig",
    "DepthEnvironment",
    "DepthProvider",
    "DEPTH_ANYTHING_V2_METRIC_MODELS",
    "FrameGraph",
    "GeometryMapper",
    "GeometryCue",
    "GeometryMorpher",
    "HapticCue",
    "HapticPattern",
    "IntrusionAnchor",
    "MetricGeometryObservation",
    "MetricGeometryProvider",
    "MotionGate",
    "MotionGateConfig",
    "MotionSample",
    "ObjectTracker",
    "OpenVocabularySegmenter",
    "PerceptualPriorityScheduler",
    "PoseProvider",
    "PriorityLane",
    "Quaternion",
    "StableManifold",
    "StaleTransformError",
    "SpeakerArrayConfig",
    "SpeakerBank",
    "SurfaceContact",
    "ScheduledCue",
    "SchedulerCounters",
    "SceneDescriber",
    "SceneDescriptionRequest",
    "SceneSimilarityGate",
    "SegmentedObservation",
    "SemanticDepthFuser",
    "SemanticGateConfig",
    "SemanticSegmenter",
    "SemanticSimilarityGate",
    "SemanticTrack",
    "TimedTransform",
    "Vec3",
    "VirtualEmitter",
    "VirtualSpeakerArray",
    "WeightedEmitter",
    "EnvelopmentField",
    "AuditoryIconCue",
    "AuditoryIconDefinition",
    "AuditoryIconRegistry",
    "MaskDepthPoint",
    "clamp01",
]

__all__ += [
    "AudioDispatch",
    "AudioOutputTopology",
    "FmodCommandAdapter",
    "GeometryOutput",
    "InspectableAudioFallback",
    "PerceptionEngine",
    "PipelineCounters",
    "SemanticOutput",
    "SpatialMap",
    "SpatializerProfile",
    "SpatialVoiceCommand",
]
